name: publish-snapshot
on:
  workflow_dispatch:
  push:
    branches: [dev, main]
jobs:
  publish-to-maven:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Repo
        uses: actions/checkout@v4
      - name: Setting up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Grant permissions to Gradle
        run: chmod +x gradlew
      - name: Publish with Gradle
        run: ./gradlew clean publish -Pmaven-user=${{ secrets.MAVEN_REPO_USER }} -Pmaven-secret=${{ secrets.MAVEN_REPO_PASS }} -Dorg.gradle.jvmargs=-Xmx512m --no-daemon